<a href="https://colab.research.google.com/github/pranithrao1/python_basics_practice/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **pandas concepts**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Salaries.csv')

In [ ]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
df.shape

(78, 6)

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
df.isnull()

     rank  discipline    phd  service    sex  salary
0   False       False  False    False  False   False
1   False       False  False    False  False   False
2   False       False  False    False  False   False
3   False       False  False    False  False   False
4   False       False  False    False  False   False
5   False       False  False    False  False   False
6   False       False  False    False  False   False
7   False       False  False    False  False   False
8   False       False  False    False  False   False
9   False       False  False    False  False   False
10  False       False  False    False  False   False
11  False       False  False    False  False   False
12  False       False  False    False  False   False
13  False       False  False    False  False   False
14  False       False  False    False  False   False
15  False       False  False    False  False   False
16  False       False  False    False  False   False
17  False       False  False    False  False   False
18  False       False  False    False  False   False
19  False       False  False    False  False   False
20  False       False  False    False  False   False
21  False       False  False    False  False   False
22  False       False  False    False  False   False
23  False       False  False    False  False   False
24  False       False  False    False  False   False
25  False       False  False    False  False   False
26  False       False  False    False  False   False
27  False       False  False    False  False   False
28  False       False  False    False  False   False
29  False       False  False    False  False   False
30  False       False  False    False  False   False
31  False       False  False    False  False   False
32  False       False  False    False  False   False
33  False       False  False    False  False   False
34  False       False  False    False  False   False
35  False       False  False    False  False   False
36  False       False  False    False  False   False
37  False       False  False    False  False   False
38  False       False  False    False  False   False
39  False       False  False    False  False   False
40  False       False  False    False  False   False
41  False       False  False    False  False   False
42  False       False  False    False  False   False
43  False       False  False    False  False   False
44  False       False  False    False  False   False
45  False       False  False    False  False   False
46  False       False  False    False  False   False
47  False       False  False    False  False   False
48  False       False  False    False  False   False
49  False       False  False    False  False   False
50  False       False  False    False  False   False
51  False       False  False    False  False   False
52  False       False  False    False  False   False
53  False       False  False    False  False   False
54  False       False  False    False  False   False
55  False       False  False    False  False   False
56  False       False  False    False  False   False
57  False       False  False    False  False   False
58  False       False  False    False  False   False
59  False       False  False    False  False   False
60  False       False  False    False  False   False
61  False       False  False    False  False   False
62  False       False  False    False  False   False
63  False       False  False    False  False   False
64  False       False  False    False  False   False
65  False       False  False    False  False   False
66  False       False  False    False  False   False
67  False       False  False    False  False   False
68  False       False  False    False  False   False
69  False       False  False    False  False   False
70  False       False  False    False  False   False
71  False       False  False    False  False   False
72  False       False  False    False  False   False
73  False       False  False    False  False   False
74  False       False  False    False  False   False
75  False       False  False    False  False   False
76  False       False  False    False  False   False
77  False       False  False    False  False   False

In [ ]:
df.isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [ ]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [ ]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
import warnings
warnings.filterwarnings('ignore')
df.mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [ ]:
df['salary'].mean()

108023.78205128205

In [ ]:
df['salary'].median()

104671.0

In [ ]:
df['salary'].mode()

0    92000
Name: salary, dtype: int64

In [ ]:
df['salary'].var()

800531254.0427907

In [ ]:
df['salary'].std()

28293.66102226417

In [ ]:
df['salary'].min()

57800

In [ ]:
df['salary'].skew()

0.45210256755588096

In [ ]:
df['salary'].kurt()

-0.4017126758820546

In [ ]:
df[['salary','phd','service']]

    salary  phd  service
0   186960   56       49
1    93000   12        6
2   110515   23       20
3   131205   40       31
4   104800   20       18
5   122400   20       20
6    81285   20       17
7   126300   18       18
8    94350   29       19
9    57800   51       51
10  128250   39       33
11  134778   23       23
12   88000    1        0
13  162200   35       33
14  153750   25       19
15  150480   17        3
16   75044    8        3
17   92000    4        0
18  107300   19        7
19  150500   29       27
20   92000    4        4
21  103106   33       30
22   73000    4        2
23   85000    2        0
24   91100   30       23
25   99418   35       31
26  148750   38       19
27  155865   45       43
28   91300    7        2
29  123683   21       20
30  107008    9        7
31  155750   22       21
32  103275   27       19
33  120000   18       18
34  119800   12        8
35  126933   28       23
36  146856   45       45
37  102000   20        8
38   91000    4        3
39  129000   18       18
40  137000   39       36
41   74830   13        8
42   80225    4        2
43   77000    5        0
44  151768   23       19
45  140096   25       25
46   74692   11        3
47  103613   11       11
48  111512   17       17
49  122960   17       18
50   97032   10        5
51  127512   20       14
52  105000   12        0
53   73500    5        3
54   62884   25       22
55   72500    2        0
56   77500   10        8
57   72500    3        1
58  144651   36       26
59  103994   12       10
60   92000    3        3
61  103750   13       10
62  109650   14        7
63   91000   29       27
64   73300   26       24
65  117555   36       19
66   63100    7        6
67   90450   17       11
68   77500    4        2
69  116450   28        7
70   78500    8        3
71   71065   12        9
72  161101   24       15
73  105450   18       10
74  104542   19        6
75  124312   17       17
76  109954   28       14
77  109646   23       15

In [ ]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [ ]:
df['rank'].value_counts()

Prof         46
AsstProf     19
AssocProf    13
Name: rank, dtype: int64

In [ ]:
df.iloc[:,:]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
df.iloc[0:50, [0,1,3]]

         rank discipline  service
0        Prof          B       49
1        Prof          A        6
2        Prof          A       20
3        Prof          A       31
4        Prof          B       18
5        Prof          A       20
6   AssocProf          A       17
7        Prof          A       18
8        Prof          A       19
9        Prof          A       51
10       Prof          B       33
11       Prof          B       23
12   AsstProf          B        0
13       Prof          B       33
14       Prof          B       19
15       Prof          B        3
16   AsstProf          B        3
17   AsstProf          B        0
18       Prof          A        7
19       Prof          A       27
20   AsstProf          B        4
21       Prof          A       30
22   AsstProf          A        2
23   AsstProf          A        0
24       Prof          A       23
25       Prof          B       31
26       Prof          A       19
27       Prof          A       43
28   AsstProf          B        2
29       Prof          B       20
30  AssocProf          B        7
31       Prof          B       21
32       Prof          A       19
33       Prof          B       18
34  AssocProf          B        8
35       Prof          B       23
36       Prof          B       45
37       Prof          A        8
38   AsstProf          B        3
39       Prof          B       18
40       Prof          A       36
41  AssocProf          A        8
42   AsstProf          B        2
43   AsstProf          B        0
44       Prof          B       19
45       Prof          B       25
46   AsstProf          B        3
47  AssocProf          B       11
48       Prof          B       17
49       Prof          B       18

In [ ]:
df1 = pd.read_csv('Salaries.csv', nrows= 1)

In [ ]:
df1

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960

In [ ]:
df[df['salary']>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [ ]:
df.groupby(['rank']).mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [ ]:
df.groupby('rank')[['salary','phd']].mean()

                  salary        phd
rank
AssocProf   91786.230769  15.076923
AsstProf    81362.789474   5.052632
Prof       123624.804348  27.065217